version: "3.8"

services:
  app:
    build:
      context: .
    container_name: faststream_app
    env_file:
      - ./.env
    command: ["make", "run-faststream"]

networks:
  default:
    external:
      name: work_network
