version: "3.8"
services:
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: ["make", "run"]

  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres_data:

networks:
  default:
    external:
      name: work_network
