version: '3'

services:

  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

networks:
  default:
    external:
      name: work_network
