"""add auction_id btree index

Revision ID: 08f75cfe8279
Revises: 161ef1ac65aa
Create Date: 2024-12-13 00:18:43.571562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f75cfe8279'
down_revision: Union[str, None] = '161ef1ac65aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auctions_auction_id'), 'auctions', ['auction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auctions_auction_id'), table_name='auctions')
    # ### end Alembic commands ###
